title: PESO 
description: The PESO Project

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.

exclude:
  - .jekyll-cache
  - README.md
  - LICENSE

collections:
  ecosystem:
    output: true
    permalink: /ecosystem/:path/